hits/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from ckeditor_uploader import views
from django.contrib.auth.decorators import permission_required
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^usuarios/', include('web.urls', namespace="usuarios")),
    url(r'^noticias/', include('post.urls', namespace="noticias")),
    url(r'^', include('song.urls', namespace="player")),
    url(r'^', include('principal.urls',namespace="principal") ),
    
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    
    url(r'^upload/', permission_required('post.change_post')(views.upload), name='ckeditor_upload'),
    url(r'^browse/', permission_required('post.change_post')(views.browse), name='ckeditor_browse'),


    #reset password
    url(r'^reset/pasword_reset$', password_reset, {'template_name':'password_reset/password_reset_form.html','email_template_name':'password_reset/password_reset_email.html'}, name='password_reset'),
    url(r'^reset/pasword_reset_done$', password_reset_done, {'template_name':'password_reset/password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)$', password_reset_confirm, {'template_name':'password_reset/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^reset/done$', password_reset_complete, {'template_name':'password_reset/password_reset_complete.html'}, name='password_reset_complete'),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

song/urls.py
from django.conf.urls import url
from .views import *
from django.contrib.auth.decorators import permission_required, login_required



urlpatterns = [
   #Admin 
    url(r'^nueva$', permission_required('song.add_song')(createSongAdmin), name='crear_cancion'),
    url(r'^editar/(?P<id>\d+)$', permission_required('song.change_song')(updateSongAdmin), name='editar_cancion'),
    url(r'^lista$', permission_required('song.change_song')(listSong), name='listar_canciones'),
    #----------album ------------
    url(r'^album/nuevo$', permission_required('song.add_song')(createAlbumAdmin), name='crear_album'),
    url(r'^album/(?P<id>\d+)/cancion$', permission_required('song.add_song')(createAlbumSongAdmin), name='crear_album_song'),
    url(r'^album/editar/(?P<id>\d+)$', permission_required('song.add_song')(updateAlbumAdmin), name='editar_album_song'),
    url(r'^album/lista$', permission_required('song.add_song')(listAlbum), name='listar_albums'),
    url(r'^album/delete/(?P<id>\d+)$', permission_required('song.add_song')(deleteAlbum), name='delete_album'),
    url(r'^ajax/getalbums/$', permission_required('song.add_song')(get_albums), name='get_albums'),

    #userArtist
    url(r'^new$', permission_required('song.add_user_song')(createSongUser), name='new_cancion'),
    url(r'^update/(?P<id>\d+)$', permission_required('song.change_user_song')(updateSongUser), name='update_cancion'),
    url(r'^delete/(?P<id>\d+)$', permission_required('song.change_user_song')(deleteSongUser), name='delete_song_user'),
    url(r'^ajax/getalbumsuser$', permission_required('song.change_user_song')(get_albums_user), name='get_albums_user'),
    url(r'^ajax/likesong$', login_required(like_song), name='like_cancion'),
    #----------album ------------
    url(r'^album/new$', permission_required('song.change_user_song')(createAlbumUser), name='crear_album_user'),
    url(r'^album/(?P<id>\d+)/new$', permission_required('song.change_user_song')(createAlbumSongUser), name='crear_album_song_user'),
    url(r'^album/update/(?P<id>\d+)$', permission_required('song.change_user_song')(updateAlbumUser), name='editar_album_user'),
    url(r'^album/delete/(?P<id>\d+)$', permission_required('song.change_user_song')(deleteAlbumUser), name='delete_album_user'),
    url(r'^album/(?P<ida>\d+)/delete/(?P<ids>\d+)$', permission_required('song.change_user_song')(deleteAlbumSongUser), name='delete_album_song_user'),
    

    url(r'^(?P<slug>[\w-]+)/$', detail, name='detail_cancion'),
    url(r'^download/(?P<id>\d+)$', download, name='download_cancion'),

    url(r'^getlink$', get_link_download, name='get_link'),
    url(r'^sum/(?P<id>\d+)$', sum, name='sum'),


    url(r'^ajax/likeartist$', login_required(follow_artist), name='follow_artist'),

    url(r'^ajax/viewsong$', view_song, name='view_song'),
    url(r'^ajax/viewplaylist$', login_required(view_playlist), name='view_playlist'),


    #----------- playList ----------------
    url(r'^playlist/nueva$', permission_required('song.add_playlist')(createPlayListAjax), name='crear_playlist_ajax'),
    url(r'^playlist/add$', permission_required('song.add_playlist')(addToPlayListAjax), name='add_Toplaylist_ajax'),
    url(r'^playlist/delete/(?P<id>\d+)$', permission_required('song.add_playlist')(deletePlayList), name='delete_playlist_ajax'),
    url(r'^playlist/(?P<idp>\d+)/delete/(?P<ids>\d+)$', permission_required('song.change_user_song')(deletePlayListSong), name='delete_playlist_song_user'),

    url(r'^ajax/getplaylist/$', login_required(getPlayList), name='get_playList'),
    url(r'^ajax/getalbumsongs/$', login_required(getAlbumSongs), name='get_album_songs'),


    
    url(r'^albums/(?P<id>\d+)$', albumList, name='detail_album'),
    url(r'^playlist/(?P<id>\d+)$', playList, name='detail_playlist'),

    #------- comentarios -------

    url(r'^ajax/comentar$', login_required(comment), name='comment_cancion'),
    url(r'^ajax/paginar$', comment_pag, name='comment_paginar'),


    url(r'^denunciar$', delation, name='delation'),

    url(r'^p$', new, name='new'),



    #Para La API
    url(r'^api/getlink$', api_get_link, name='api_get_link'),

]

"""permission_required('song.add_song')"""

web/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login 
from web import views

from django.contrib.auth.decorators import login_required
#from .views import Sign_in

urlpatterns = [
    #url(r'^login$', login,{'template_name':'usuarios/login.html'}, name = 'login'),
    url(r'^login$', views.log_in, name = 'login'),
    url(r'^register$', views.register, name = 'register_select'),
    url(r'^register/usuario$', views.sign_up, name = 'register'),
    url(r'^register/musico$', views.sign_up_artist, name = 'register_musician'),
    url(r'^logout', login_required(views.log_out), name='logout'),

    url(r'^ajax/user$', views.user, name='img_user'),

    url(r'^profile/(?P<username>\w+)$', views.profile, name='profile'),
    url(r'^profile/(?P<username>\w+)/editar$', login_required(views.editProfile), name='edit_profile'),
    url(r'^profile/(?P<username>\w+)/aeditar$', login_required(views.editArtistProfile), name='edit_artist_profile'),


    url(r'^ajax/followuser$', login_required(views.follow_user), name='follow_user'),

    url(r'^profile/(?P<username>\w+)/albums$', views.albums, name='albums_user'),
    url(r'^profile/(?P<username>\w+)/playlists$', views.playlists, name='playlists_user'),
    url(r'^profile/(?P<username>\w+)/favoritas$', views.favorites, name='favorites_user'),
    url(r'^profile/(?P<username>\w+)/albums/(?P<id>\d+)$', views.albumList, name='albumList_user'),
    url(r'^profile/(?P<username>\w+)/playlists/(?P<id>\d+)$', views.playList, name='playList_user'),
    url(r'^profile/(?P<username>\w+)/canciones$', views.songs, name='songs_user'),
    url(r'^profile/(?P<username>\w+)/descargas$', login_required(views.dowmloads), name='downloads_user'),
    url(r'^profile/(?P<username>\w+)/seguidos$', login_required(views.following), name='following_user'),
    url(r'^profile/(?P<username>\w+)/seguidores$', login_required(views.followers), name='followers_user'),
]

song/models.py
from django.db import models
from web.validators import valid_extension, valid_extension_mp3
import os
from django.template import defaultfilters
import datetime
from django.conf import settings



YEAR_CHOICES = []
for r in range(1930, (datetime.datetime.now().year+1)):
    YEAR_CHOICES.append((r,r))


def generate_path(instance, filename):
    folder = "song_" + str(instance.user) 
    return os.path.join("adjuntos", folder, filename)   


class Genre(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=40, unique=True)
    
    def __str__(self):
        return self.name
     
class Artist(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=40)
    photo = models.ImageField(blank=False, null=False, upload_to=settings.URL_MYMEDIA+'artist/photos', validators=[valid_extension], default = 'static/images/default-profile.png')
    
    followers = models.ManyToManyField('web.Usuario', symmetrical = True, blank=True)
    
    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if (hasattr(self, "artist")):
            self.name = self.artist.stage_name
            self.photo = self.artist.photo
        
        super(Artist, self).save(*args, **kwargs)

from datetime import date
from django.utils import timezone

class Album(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=40)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE, blank = False, null=False)
    photo = models.ImageField(blank=False, null=False, upload_to=settings.URL_MYMEDIA+'album/photos', validators=[valid_extension])
    release_date = models.DateField(default=timezone.now(), null = False, blank = False)
    
    slug = models.SlugField(max_length=100, blank = True)
    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = defaultfilters.slugify(self.name)
            super(Album, self).save(*args, **kwargs)
    
    def __str__(self):
        return self.name

    class Meta:
        permissions = (
            # Permission identifier     human-readable permission name
            
            ("add_user_album",          "Can user add album"),
            ("change_user_album",       "Can user change album"),
            ("delete_user_album",       "Can user delete album"),
        )
        unique_together = ('name', 'artist',)


from datetime import timedelta
from django.utils import timezone
# Create your models here.
class Song(models.Model):
    file = models.FileField(null = True, blank = True,upload_to=settings.URL_MYMEDIA+'songs/music',validators=[valid_extension_mp3])
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=40)
    id_youtube = models.CharField(max_length=11, unique = True)
    link_download = models.CharField(max_length=150, blank = True)
    photo = models.ImageField(blank=False, null=False, upload_to=settings.URL_MYMEDIA+'songs/photos', validators=[valid_extension])
    release_date = models.DateField(default=date.today(), null = False, blank = True)
    lyric =  models.TextField(null = True, blank = True)
    duration = models.DurationField(default=timedelta(), blank=True, null=False)

    genre = models.ForeignKey(Genre, on_delete=models.PROTECT)
    time_stamp = models.DateTimeField(auto_now=True)
    artists = models.ManyToManyField(Artist, blank = True)
    
    album = models.ForeignKey(Album, null = True , blank = True, on_delete=models.SET_NULL)
    
    num_downloads = models.IntegerField(default=0, blank=True)

    downloads = models.ManyToManyField('web.Usuario', symmetrical = True, related_name="downloads")
    
    likes = models.ManyToManyField('web.Usuario', symmetrical = True, blank=True)
    slug = models.SlugField(max_length=100, blank = True, unique = True)

    def save(self, *args, **kwargs):
        self.slug = defaultfilters.slugify(self.name  + ' ' + str(self.id_youtube) )   
        super(Song, self).save(*args, **kwargs)
    
    def __str__(self):
        return self.name
    
    class Meta:
        permissions = (
            # Permission identifier     human-readable permission name
            
            ("add_user_song",          "Can user add song"),
            ("change_user_song",       "Can user change song"),
            ("delete_user_song",       "Can user delete song"),
        )     

class Comment_Song (models.Model):
    id = models.AutoField(primary_key=True)
    content = models.TextField()
    time_stamp = models.DateTimeField(auto_now_add=True, blank=True)
    
    author = models.ForeignKey("web.Usuario", null = False , blank = True, on_delete=models.DO_NOTHING)
    song = models.ForeignKey(Song, null = False , blank = True, on_delete=models.CASCADE)



class PlayList(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=40)
    songs = models.ManyToManyField(Song, blank=True)
    user = models.ForeignKey('web.Usuario', blank = True, on_delete=models.CASCADE)
    private = models.BooleanField(blank = True, default=False, null=False)
    
    def __str__(self):
        return self.name
    
class View(models.Model):
    """docstring for Views"""
    country = models.CharField(max_length=40)
    date = models.DateField(default=date.today(), blank=True)
    song = models.ForeignKey(Song, blank=True, null=True, on_delete=models.CASCADE)
    playlist = models.ForeignKey(PlayList, blank=True, null=True, on_delete=models.CASCADE)   
    
    
    
    
    
    
    
    
    
    

web/models.py
from django.db import models
from django.contrib.auth.models import User
from django_countries.fields import CountryField
import os
from .validators import valid_extension

from django.conf import settings
from song.models import Artist
# Create your models here.


def generate_path(instance, filename):
    folder = "modelo_" + str(instance.user) 
    return os.path.join("adjuntos", folder, filename)   
    
class Usuario(User):
    country = CountryField()
    birthdate = models.DateField(null = False, blank = False)
    photo = models.ImageField(blank=True, null=True, upload_to=settings.URL_MYMEDIA+'users/photo', validators=[valid_extension], default = 'static/images/default-profile.png')
    front = models.ImageField(blank=True, null=True, upload_to=settings.URL_MYMEDIA+'users/front', validators=[valid_extension],default = 'static/images/default-post.jpg')
    description = models.TextField(blank = True, null = True)
    name = models.CharField(max_length=150, blank = True, null = True)
    website = models.URLField(blank = True, null = True)
    instagram = models.CharField(max_length=150, blank = True, null = True)

    relationships = models.ManyToManyField("self", symmetrical = False, blank = True, through='Relationship', related_name='related_to')

    def add_relationship(self, person, status):
        relationship, created = Relationship.objects.get_or_create(
            from_person=self,
            to_person=person,
            status=status)
        return created

    def remove_relationship(self, person, status):
        Relationship.objects.filter(
            from_person=self,
            to_person=person,
            status=status).delete()
        return

    def get_relationships(self, status):
        return self.relationships.filter(
            to_people__status=status,
            to_people__from_person=self)

    def get_related_to(self, status):
        return self.related_to.filter(
            from_people__status=status,
            from_people__to_person=self)

    @property
    def get_following(self):
        return self.get_relationships(RELATIONSHIP_FOLLOWING)

    @property
    def get_followers(self):
        return self.get_related_to(RELATIONSHIP_FOLLOWING)

    def get_friends(self):
        return self.relationships.filter(
            to_people__status=RELATIONSHIP_FOLLOWING,
            to_people__from_person=self,
            from_people__status=RELATIONSHIP_FOLLOWING,
            from_people__to_person=self)


RELATIONSHIP_FOLLOWING = 1
RELATIONSHIP_BLOCKED = 2
RELATIONSHIP_STATUSES = (
    (RELATIONSHIP_FOLLOWING, 'Following'),
    (RELATIONSHIP_BLOCKED, 'Blocked'),
)

class Relationship(models.Model):
    from_person = models.ForeignKey(Usuario, related_name='from_people')
    to_person = models.ForeignKey(Usuario, related_name='to_people')
    status = models.IntegerField(choices=RELATIONSHIP_STATUSES)
    
class UserArtist(Usuario): 
    
    stage_name = models.CharField(max_length=30)
    singer = models.OneToOneField(Artist, on_delete=models.DO_NOTHING, blank = True, null = True, related_name='artist')
    
    def save(self, *args, **kwargs):
        if(self.singer is None):
            artist = Artist()
            artist.name = self.stage_name
            artist.save()
            self.singer = artist

        super(UserArtist, self).save(*args, **kwargs)
        self.singer.save()

User._meta.get_field('email').blank = False
    

        

templates/usuarios/profile.html
{% extends 'base.html' %}


{% block title %}
{{usuario.name|default_if_none:usuario.username}} - Hits Música
{% endblock %}

{% block styles %}
<div id="target-style">
    <link rel="stylesheet" href="/static/css/profile2.css">
</div>
{% endblock %}


{% block body %}

<div id="target-body">
<div class="mainbody container-fluid">
    <div class="row">
          <span>
        <div class="fb-profile">
        <img align="left" class="fb-image-lg" src="/{{usuario.front}}" alt="Profile image example"/>
        <img align="left" class="fb-image-profile thumbnail" src="/{{usuario.photo}}" alt="Profile image example"/>
        <div class="fb-profile-text">
            <h1>{{usuario.name|default_if_none:usuario.username}}</h1>
            <p>{{usuario.website|default_if_none:''}}</p>
            <p>{{usuario.instagram|default_if_none:''}}</p>
            <p>{{usuario.description|default_if_none:''}}</p>
            <p>{{usuario.get_followers.all.count}} seguidores </p>
            <p>{{usuario.get_following.all.count}} seguidos </p>
            {% if request.user.username != usuario.username %}
                {% if follow %}
                <button class="btn btn-primary btn-min-block"  onclick="follow({{usuario.pk}},'{{artist}}');" >Dejar de Seguir</button>
                {% else %}
                <button class="btn btn-primary btn-min-block"  onclick="follow({{usuario.pk}},'{{artist}}');" >Seguir</button>
                {% endif %}
            {% else %}
                {% if artist %}
                <a class="btn btn-primary btn-min-block" href="{{request.user.username}}/aeditar">Editar</a>
                {% else %}
                <a class="btn btn-primary btn-min-block" href="{{request.user.username}}/editar">Editar</a>
                {% endif %}
            {% endif %}
        </div>
        </div> 
                    </span>
        <div style="padding-top:50px;"> </div>
        <div class="col-lg-3 col-md-3 ">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="media">
                       
                        <div class="media-body">
                            <hr>
                            <h3><strong>Informacion Personal</strong></h3>
                            <p>{{usuario.description}}</p>
                            <hr>
                            <h3><strong>Rol</strong></h3>
                            <p>{{usuario.groups.all|join:" - "}}</p>
                            <hr>
                            <h3><strong>Listas de Reproduccion</strong></h3>
                            <p>{{usuario.playlist_set.all.count}} Listas</p>
                            <hr>
                            {% if artist %}
                                <h3><strong>Canciones</strong></h3>
                                <p>{{usuario.singer.song_set.all.count}} Canciones</p>
                                <hr>
                                <h3><strong>Albumes</strong></h3>
                                <p>{{usuario.singer.album_set.all.count}} Albumes</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
         
        <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12 ">



       
               
                  
                   
                    
               
      
           
            <!-- Ultimas Canciones del usuario. -->
            
{% if artist %}
<div class="panel panel-default">
    <div class="panel-body">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12">
                    <div class="section-title text-center">
                            <h3>Ultimas Canciones</h3>
                            <p></p>
                            <a class="btn btn-primary btn-min-block" href="{% url 'usuarios:songs_user' usuario.username%}">Ver todas</a>
                        </div>
                </div>
            </div>
            
            <div class="row">
                <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-1">
                    <div id="team-section">
                    
                        
                
                

                                <div class="our-team">
                                    {% for cancion in usuario.singer.song_set.all|slice:":6" %}
                                    <div class="team-member">
                                        <img src="/{{cancion.photo}}" class="img-responsive" alt="">
                                        <div class="team-details">
                                            <h4>{{cancion.name}}</h4>
                                            <p>{{ cancion.artists.all|join:"  X " }}</p>
                                            <ul>
                                                <li><a href="{% url 'player:detail_cancion' cancion.slug %}"><i class="fa fa-arrow-circle-o-down" target="_blank" data-toggle="tooltip" title="Descargar"></i></a></li>
                                                <li><a href=""  data-ajax="true" data-name="{{cancion.name}}" data-id="{{cancion.id}}" data-photo="{{cancion.photo}}" data-toggle="tooltip" title="Reproducir" class="only-play"><i class="fa fa-play "></i></a></li>
                                            </ul>
                                        </div>
                                    </div>
                                    {% empty %}
                                        <div> No hay canciones</div>
                                    {% endfor %}
                                </div>
                    </div>
                </div>
            </div>
                
        </div>
    </div>
 </div>
<!--Fin Canciones del usuario-->


<div class="panel panel-default">
    <div class="panel-body">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12">
                    <div class="section-title text-center">
                            <h3>Ultimos Albums</h3>
                            <p></p>
                            <a class="btn btn-primary btn-min-block" href="{% url 'usuarios:albums_user' usuario.username %}">Ver todos</a>
                        </div>
                </div>
            </div>
            
            <div class="row">
                <div class="col-md-11">
                    <div id="team-section">
                    
                        
                
                

                                <div class="our-team">
                                    {% for album in usuario.singer.album_set.all|slice:":6" %}
                                    <div class="team-member">
                                        <img src="/{{album.photo}}" class="img-responsive" alt="">
                                        <div class="team-details">
                                            <h4>{{album.name}}</h4>
                                            <ul>
                                                <li><a href="{% url 'usuarios:albumList_user' usuario.username album.id %}" data-toggle="tooltip" title="Ver"><i class="fa fa-eye"></i></a></li>
                                          
                                            </ul>
                                        </div>
                                    </div>
                                    {% empty %}
                                        <div> No hay albumes </div>
                                    {% endfor %}


                                </div>

                    
                    </div>
                </div>
            </div>
                
        </div>
    </div>
 </div>

{% endif %}


<!--Listas de reproduccion Usuario-->
    <div class="panel panel-default">
    <div class="panel-body">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12">
                    <div class="section-title text-center">
                            <h3>Listas</h3>
                            <p></p>
                            <a class="btn btn-primary btn-min-block" href="{% url 'usuarios:playlists_user' usuario.username %}">Ver todas</a>
                        </div>
                </div>
            </div>
            
            <div class="row">
                <div class="col-md-11">
                    <div id="team-section">
                    
                        
                
                

                                <div class="our-team">
                                    {% for list in usuario.playlist_set.all|slice:":3" %}
                                    <div class="team-member">
                                        {% if list.songs.first is None %}
                                        <img src="/static/images/logos/logo2.png" class="img-responsive" alt="">
                                        {% else %}
                                        <img src="/{{list.songs.first.photo|default_if_none:'static/images/logos/logo2'}}" class="img-responsive" alt="">
                                        {% endif %}
                                        <div class="team-details">
                                            <h4>{{list.name}} </h4>
                                            <ul>
                                                <li><a href="{% url 'usuarios:playList_user' usuario.username list.id %}" data-toggle="tooltip" title="Ver"><i class="fa fa-eye"></i></a></li>
                                            
                                            </ul>
                                        </div>
                                    </div>
                                    {% empty %}
                                        <div> No hay Listas creadas </div>
                                    {% endfor %}


                                </div>

                    
                    </div>
                </div>
            </div>
                
        </div>
    </div>
 </div>

<!--fin listas de reproduccion usuario-->




<div class="panel panel-default">
    <div class="panel-body">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12">
                    <div class="section-title text-center">
                            <h3>Favoritas</h3>
                            <p></p>
                            <a class="btn btn-primary btn-min-block" href="{% url 'usuarios:favorites_user' usuario.username %}">Ver todas</a>
                        </div>
                </div>
            </div>
            
            <div class="row">
                <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-1">
                    <div id="team-section">
                    
                        
                
                

                                <div class="our-team">
                                    {% for cancion in usuario.song_set.all|slice:":6" %}
                                    <div class="team-member">
                                        <img src="/{{cancion.photo}}" class="img-responsive" alt="">
                                        <div class="team-details">
                                            <h4>{{cancion.name}}</h4>
                                            <p>{{cancion.artists.all|join:"  X " }}</p>
                                            <ul>
                                                <li><a href="{% url 'player:detail_cancion' cancion.slug %}"><i class="fa fa-arrow-circle-o-down" target="_blank" data-toggle="tooltip" title="Descargar"></i></a></li>
                                                <li><a href=""  data-ajax="true" data-name="{{cancion.name}}" data-id="{{cancion.id}}" data-photo="{{cancion.photo}}" data-toggle="tooltip" title="Reproducir" class="only-play"><i class="fa fa-play "></i></a></li>
                                            </ul>
                                        </div>
                                    </div>
                                    {% empty %}
                                        <div> No hay favoritos</div>
                                    {% endfor %}


                                </div>

                    
                    </div>
                </div>
            </div>
                
        </div>
    </div>
 </div>
<!--fin listas de reproduccion usuario-->
           
    </div>
    </div>
</div>

</div>
{% endblock %}

{% block scripts %}

<div id="target-script">

    <script src="/static/js/owl.carousel.min.js"></script>
    <script src="/static/js/jquery.fitvids.js"></script>
    <script src="/static/js/styleswitcher.js"></script>
    <!-- Custom Theme JavaScript --> 
    <script src="/static/js/script.js"></script>
    
<script type="text/javascript">

    function follow(id, artist){
        b = artist == 'True';
        alert(b);
        $.ajax({
            type: 'POST',
            url: "{% url 'usuarios:follow_user' %}",
            data: {'id' : id, 'artist':b},
            dataType: 'json',
            success: function (data) {
                alert(data.add);
                if (data.r){
                    var seg = parseInt($("."+id+".seguidores").text());
                    if (data.add)
                        $("."+id+".seguidores").text(seg+1);
                    else
                        $("."+id+".seguidores").text(seg-1);
                }
            }
          });
    }
</script>

</div>
{% endblock %}