hits/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from ckeditor_uploader import views
from django.contrib.auth.decorators import permission_required
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^usuarios/', include('web.urls', namespace="usuarios")),
    url(r'^noticias/', include('post.urls', namespace="noticias")),
    url(r'^', include('song.urls', namespace="player")),
    url(r'^', include('principal.urls',namespace="principal") ),
    
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    
    url(r'^upload/', permission_required('post.change_post')(views.upload), name='ckeditor_upload'),
    url(r'^browse/', permission_required('post.change_post')(views.browse), name='ckeditor_browse'),


    #reset password
    url(r'^reset/pasword_reset$', password_reset, {'template_name':'password_reset/password_reset_form.html','email_template_name':'password_reset/password_reset_email.html'}, name='password_reset'),
    url(r'^reset/pasword_reset_done$', password_reset_done, {'template_name':'password_reset/password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)$', password_reset_confirm, {'template_name':'password_reset/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^reset/done$', password_reset_complete, {'template_name':'password_reset/password_reset_complete.html'}, name='password_reset_complete'),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

song/urls.py
from django.conf.urls import url
from .views import *
from django.contrib.auth.decorators import permission_required, login_required



urlpatterns = [
   #Admin 
    url(r'^nueva$', permission_required('song.add_song')(createSongAdmin), name='crear_cancion'),
    url(r'^editar/(?P<id>\d+)$', permission_required('song.change_song')(updateSongAdmin), name='editar_cancion'),
    url(r'^lista$', permission_required('song.change_song')(listSong), name='listar_canciones'),
    #----------album ------------
    url(r'^album/nuevo$', permission_required('song.add_song')(createAlbumAdmin), name='crear_album'),
    url(r'^album/(?P<id>\d+)/cancion$', permission_required('song.add_song')(createAlbumSongAdmin), name='crear_album_song'),
    url(r'^album/editar/(?P<id>\d+)$', permission_required('song.add_song')(updateAlbumAdmin), name='editar_album_song'),
    url(r'^album/lista$', permission_required('song.add_song')(listAlbum), name='listar_albums'),
    url(r'^album/delete/(?P<id>\d+)$', permission_required('song.add_song')(deleteAlbum), name='delete_album'),
    url(r'^ajax/getalbums/$', permission_required('song.add_song')(get_albums), name='get_albums'),

    #userArtist
    url(r'^new$', permission_required('song.add_user_song')(createSongUser), name='new_cancion'),
    url(r'^update/(?P<id>\d+)$', permission_required('song.change_user_song')(updateSongUser), name='update_cancion'),
    url(r'^delete/(?P<id>\d+)$', permission_required('song.change_user_song')(deleteSongUser), name='delete_song_user'),
    url(r'^ajax/getalbumsuser$', permission_required('song.change_user_song')(get_albums_user), name='get_albums_user'),
    url(r'^ajax/likesong$', login_required(like_song), name='like_cancion'),
    #----------album ------------
    url(r'^album/new$', permission_required('song.change_user_song')(createAlbumUser), name='crear_album_user'),
    url(r'^album/(?P<id>\d+)/new$', permission_required('song.change_user_song')(createAlbumSongUser), name='crear_album_song_user'),
    url(r'^album/update/(?P<id>\d+)$', permission_required('song.change_user_song')(updateAlbumUser), name='editar_album_user'),
    url(r'^album/delete/(?P<id>\d+)$', permission_required('song.change_user_song')(deleteAlbumUser), name='delete_album_user'),
    url(r'^album/(?P<ida>\d+)/delete/(?P<ids>\d+)$', permission_required('song.change_user_song')(deleteAlbumSongUser), name='delete_album_song_user'),
    

    url(r'^(?P<slug>[\w-]+)/$', detail, name='detail_cancion'),
    url(r'^download/(?P<id>\d+)$', download, name='download_cancion'),

    url(r'^getlink$', get_link_download, name='get_link'),
    url(r'^sum/(?P<id>\d+)$', sum, name='sum'),


    url(r'^ajax/likeartist$', login_required(follow_artist), name='follow_artist'),

    url(r'^ajax/viewsong$', view_song, name='view_song'),
    url(r'^ajax/viewplaylist$', login_required(view_playlist), name='view_playlist'),


    #----------- playList ----------------
    url(r'^playlist/nueva$', permission_required('song.add_playlist')(createPlayListAjax), name='crear_playlist_ajax'),
    url(r'^playlist/add$', permission_required('song.add_playlist')(addToPlayListAjax), name='add_Toplaylist_ajax'),
    url(r'^playlist/delete/(?P<id>\d+)$', permission_required('song.add_playlist')(deletePlayList), name='delete_playlist_ajax'),
    url(r'^playlist/(?P<idp>\d+)/delete/(?P<ids>\d+)$', permission_required('song.change_user_song')(deletePlayListSong), name='delete_playlist_song_user'),

    url(r'^ajax/getplaylist/$', login_required(getPlayList), name='get_playList'),
    url(r'^ajax/getalbumsongs/$', login_required(getAlbumSongs), name='get_album_songs'),


    
    url(r'^albums/(?P<id>\d+)$', albumList, name='detail_album'),
    url(r'^playlist/(?P<id>\d+)$', playList, name='detail_playlist'),

    #------- comentarios -------

    url(r'^ajax/comentar$', login_required(comment), name='comment_cancion'),
    url(r'^ajax/paginar$', comment_pag, name='comment_paginar'),


    url(r'^denunciar$', delation, name='delation'),

    url(r'^p$', new, name='new'),



    #Para La API
    url(r'^api/getlink$', api_get_link, name='api_get_link'),

]

"""permission_required('song.add_song')"""

web/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login 
from web import views

from django.contrib.auth.decorators import login_required
#from .views import Sign_in

urlpatterns = [
    #url(r'^login$', login,{'template_name':'usuarios/login.html'}, name = 'login'),
    url(r'^login$', views.log_in, name = 'login'),
    url(r'^register$', views.register, name = 'register_select'),
    url(r'^register/usuario$', views.sign_up, name = 'register'),
    url(r'^register/musico$', views.sign_up_artist, name = 'register_musician'),
    url(r'^logout', login_required(views.log_out), name='logout'),

    url(r'^ajax/user$', views.user, name='img_user'),

    url(r'^profile/(?P<username>\w+)$', views.profile, name='profile'),
    url(r'^profile/(?P<username>\w+)/editar$', login_required(views.editProfile), name='edit_profile'),
    url(r'^profile/(?P<username>\w+)/aeditar$', login_required(views.editArtistProfile), name='edit_artist_profile'),


    url(r'^ajax/followuser$', login_required(views.follow_user), name='follow_user'),

    url(r'^profile/(?P<username>\w+)/albums$', views.albums, name='albums_user'),
    url(r'^profile/(?P<username>\w+)/playlists$', views.playlists, name='playlists_user'),
    url(r'^profile/(?P<username>\w+)/favoritas$', views.favorites, name='favorites_user'),
    url(r'^profile/(?P<username>\w+)/albums/(?P<id>\d+)$', views.albumList, name='albumList_user'),
    url(r'^profile/(?P<username>\w+)/playlists/(?P<id>\d+)$', views.playList, name='playList_user'),
    url(r'^profile/(?P<username>\w+)/canciones$', views.songs, name='songs_user'),
    url(r'^profile/(?P<username>\w+)/descargas$', login_required(views.dowmloads), name='downloads_user'),
    url(r'^profile/(?P<username>\w+)/seguidos$', login_required(views.following), name='following_user'),
    url(r'^profile/(?P<username>\w+)/seguidores$', login_required(views.followers), name='followers_user'),
]

song/models.py
from django.db import models
from web.validators import valid_extension, valid_extension_mp3
import os
from django.template import defaultfilters
import datetime
from django.conf import settings



YEAR_CHOICES = []
for r in range(1930, (datetime.datetime.now().year+1)):
    YEAR_CHOICES.append((r,r))


def generate_path(instance, filename):
    folder = "song_" + str(instance.user) 
    return os.path.join("adjuntos", folder, filename)   


class Genre(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=40, unique=True)
    
    def __str__(self):
        return self.name
     
class Artist(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=40)
    photo = models.ImageField(blank=False, null=False, upload_to=settings.URL_MYMEDIA+'artist/photos', validators=[valid_extension], default = 'static/images/default-profile.png')
    
    followers = models.ManyToManyField('web.Usuario', symmetrical = True, blank=True)
    
    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if (hasattr(self, "artist")):
            self.name = self.artist.stage_name
            self.photo = self.artist.photo
        
        super(Artist, self).save(*args, **kwargs)

from datetime import date
from django.utils import timezone

class Album(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=40)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE, blank = False, null=False)
    photo = models.ImageField(blank=False, null=False, upload_to=settings.URL_MYMEDIA+'album/photos', validators=[valid_extension])
    release_date = models.DateField(default=timezone.now(), null = False, blank = False)
    
    slug = models.SlugField(max_length=100, blank = True)
    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = defaultfilters.slugify(self.name)
            super(Album, self).save(*args, **kwargs)
    
    def __str__(self):
        return self.name

    class Meta:
        permissions = (
            # Permission identifier     human-readable permission name
            
            ("add_user_album",          "Can user add album"),
            ("change_user_album",       "Can user change album"),
            ("delete_user_album",       "Can user delete album"),
        )
        unique_together = ('name', 'artist',)


from datetime import timedelta
from django.utils import timezone
# Create your models here.
class Song(models.Model):
    file = models.FileField(null = True, blank = True,upload_to=settings.URL_MYMEDIA+'songs/music',validators=[valid_extension_mp3])
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=40)
    id_youtube = models.CharField(max_length=11, unique = True)
    link_download = models.CharField(max_length=150, blank = True)
    photo = models.ImageField(blank=False, null=False, upload_to=settings.URL_MYMEDIA+'songs/photos', validators=[valid_extension])
    release_date = models.DateField(default=date.today(), null = False, blank = True)
    lyric =  models.TextField(null = True, blank = True)
    duration = models.DurationField(default=timedelta(), blank=True, null=False)

    genre = models.ForeignKey(Genre, on_delete=models.PROTECT)
    time_stamp = models.DateTimeField(auto_now=True)
    artists = models.ManyToManyField(Artist, blank = True)
    
    album = models.ForeignKey(Album, null = True , blank = True, on_delete=models.SET_NULL)
    
    num_downloads = models.IntegerField(default=0, blank=True)

    downloads = models.ManyToManyField('web.Usuario', symmetrical = True, related_name="downloads")
    
    likes = models.ManyToManyField('web.Usuario', symmetrical = True, blank=True)
    slug = models.SlugField(max_length=100, blank = True, unique = True)

    def save(self, *args, **kwargs):
        self.slug = defaultfilters.slugify(self.name  + ' ' + str(self.id_youtube) )   
        super(Song, self).save(*args, **kwargs)
    
    def __str__(self):
        return self.name
    
    class Meta:
        permissions = (
            # Permission identifier     human-readable permission name
            
            ("add_user_song",          "Can user add song"),
            ("change_user_song",       "Can user change song"),
            ("delete_user_song",       "Can user delete song"),
        )     

class Comment_Song (models.Model):
    id = models.AutoField(primary_key=True)
    content = models.TextField()
    time_stamp = models.DateTimeField(auto_now_add=True, blank=True)
    
    author = models.ForeignKey("web.Usuario", null = False , blank = True, on_delete=models.DO_NOTHING)
    song = models.ForeignKey(Song, null = False , blank = True, on_delete=models.CASCADE)



class PlayList(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=40)
    songs = models.ManyToManyField(Song, blank=True)
    user = models.ForeignKey('web.Usuario', blank = True, on_delete=models.CASCADE)
    private = models.BooleanField(blank = True, default=False, null=False)
    
    def __str__(self):
        return self.name
    
class View(models.Model):
    """docstring for Views"""
    country = models.CharField(max_length=40)
    date = models.DateField(default=date.today(), blank=True)
    song = models.ForeignKey(Song, blank=True, null=True, on_delete=models.CASCADE)
    playlist = models.ForeignKey(PlayList, blank=True, null=True, on_delete=models.CASCADE)   
    
    
    
    
    
    
    
    
    
    

templates/song/admin/create.html
{% extends 'base.html' %}

{% block title %}
{{title}} - Hits Música
{% endblock %}

{% block styles %}
<div id="target-style">
	<link href="/static/css/formularios/formularios.css" rel="stylesheet">
	<link href="/static/css/sol.css" rel="stylesheet">
</div>
{% endblock %}

{% block body %}

<div id="target-body">
<div class="container">
    <div class="row col-md-8 col-md-offset-2 registeration">
    
        <div class="registerInner">
            <div class="col-md-12">
                <h3 class="headerSign">SUBIR CANCION</h3>
            </div>
			
			
			<center><span class="errorlist">{{mensaje}}</span></center> 
			<form method="post" id="form" action="{{action}}" enctype="multipart/form-data" >
				{% csrf_token %}

				<div class="col-xs-12 col-md-6 wow animated slideInLeft" data-wow-delay=".5s">
					<center>
							{{form.name.errors}}
							<input type="text" name="name" class="form-group" placeholder="Título" value="{{form.name.value|default_if_none:''}}" maxlength="40" id="id_name" />

							{{form.id_youtube.errors}}
							<input type="text" name="id_youtube" class="form-group" placeholder="Id de youtube" value="{{form.id_youtube.value|default_if_none:''}}" maxlength="30" id="id_id_youtube" />
						
						<div class="form-group">
							<label for="id_genre">Género:</label>
							{{form.genre.errors}}
							{{form.genre}}
						</div>

						<div class="form-group">
							<label for="id_artists">Cantantes:</label>
							{{form.artists.errors}}
							{{form.artists}}
						</div>

						<div class="form-group">
							<label for="id_album">Album:</label>
							{{form.album.errors}}
							<select name="album" id="id_album" class="select-form">
								<option value="0">form</option>
							</select>
						</div>
						
					</center>
				</div>

				<div class="col-xs-12 col-md-6 wow animated slideInRight" data-wow-delay=".5s">
					<center>
						<div class="form-group">
							{{form.release_date.errors}}
							{{form.release_date}}
						</div>
					
				        <div id="div_id_photo">
							<label for="">Portada:</label>

							<p class="errorlist">{{form.photo.errors}}</p>

							<input type="file" name="photo" class="inputfile inputfile-1" onchange="upload_img(this);" id="id_photo" />
							<label for="id_photo">
		                        <svg xmlns="http://www.w3.org/2000/svg" class="iborrainputfile" width="20" height="17" viewBox="0 0 20 17"><path d="M10 0l-5.2 4.9h3.3v5.1h3.8v-5.1h3.3l-5.2-4.9zm9.3 11.5l-3.2-2.1h-2l3.4 2.6h-3.5c-.1 0-.2.1-.2.1l-.8 2.3h-6l-.8-2.2c-.1-.1-.1-.2-.2-.2h-3.6l3.4-2.6h-2l-3.2 2.1c-.4.3-.7 1-.6 1.5l.6 3.1c.1.5.7.9 1.2.9h16.3c.6 0 1.1-.4 1.3-.9l.6-3.1c.1-.5-.2-1.2-.7-1.5z"></path></svg>
		                        <span class="iborrainputfile">Seleccionar imagen</span>
	                        </label>
	                        <br />
							<div class="img" style="display: none;"></div>
				        </div>
			        </center>
			    </div><!-- End Right Inputs -->


				<div class="col-xs-12 wow animated slideInTop" data-wow-delay=".5s">
					<center>
						<label for="id_lyric">Letra:</label>
						{{form.lyric.errors}}
						<div class="django-ckeditor-widget" data-field-id="id_lyric" style="display: inline-block;" data-ckeditor-basepath="/static/ckeditor/ckeditor/">
						    <textarea cols="40" id="id_lyric" name="lyric" rows="10" data-processed="0" data-config='{"skin": "moono-lisa", "toolbar_Basic": [["Source", "-", "Bold", "Italic"]], "toolbar_Full": [["Styles", "Format", "Bold", "Italic", "Underline", "Strike", "SpellChecker", "Undo", "Redo"], ["Link", "Unlink", "Anchor"], ["Image", "Flash", "Table", "HorizontalRule"], ["TextColor", "BGColor"], ["Smiley", "SpecialChar"], ["Source"]], "toolbar": "full", "height": 291, "width": "auto", "filebrowserWindowWidth": 940, "filebrowserWindowHeight": 725, "language": "es"}' data-external-plugin-resources='[]' data-id="id_lyric" value="{{form.lyric.value|default_if_none:''}}" class="select-form" data-type="ckeditortype"></textarea>
						</div>
					</center>
				</div>

				<div class="col-xs-12" data-wow-delay=".5s">
        <center>
        <strong class="loader-porcent"></strong>
        <div style="display: none;" class="loader"></div></center>
        </div>

				<div class="relative fullwidth col-xs-12">
					<center>
						<input type="submit" value="Guardar" id="guardar" class="signbuttons btn btn-primary" name="guardar">
					</center>
				</div>

			</form>
        </div>
        
    </div>
</div>
</div>
{% endblock %}




{% block scripts %}
<div id="target-script">
<script type="text/javascript" src="/static/ckeditor/ckeditor/ckeditor.js" async="async"></script>
<script type="text/javascript" src="/static/ckeditor/ckeditor-init.js" async="async"></script>
<script type="text/javascript" src="/static/js/app/custom-file-input.js"></script>
<script type="text/javascript" src="/static/js/app/sol.js"></script>

<script type="text/javascript">
	(function() {

		$("#id_artists").searchableOptionList({
			maxHeight:'300px'
		});
	    $("#id_artists").change(function() {
	    	
	    	smart_select();
	    }); 
	    
	}).call(this);
	
	(function() {
		
		if ("{{ photo }}" != ""){
			$('#img_id').remove();
			$("#div_id_photo .img").css("display","block");
	    	$("#div_id_photo .img").append('<img id="img_id" src="/{{photo}}" alt="" />');
		}
    	
    	smart_select();

	}).call(this);
	
	function smart_select(){
		var artists_id = $("#id_artists").val();
        // Empty the second <select>
        
        $('#id_album').empty();
        $('#id_album').append('<option value="0">Selecione una opcion </option>');
        
        $.ajax({
        	type: 'GET',
        
            url: "{% url 'player:get_albums' %}",
            data: { 'artists': artists_id },
            dataType: 'json',
            success: function (data) {
            	for (var i = 0; i <= data.length; i++) {
            		if (data[i]["id"] == {{album_id}}){
                    	$('#id_album').append('<option value="' + data[i]["id"] + '" selected>' + data[i]["name"] + '</option>');
            		}else{
            			$('#id_album').append('<option value="' + data[i]["id"] + '">' + data[i]["name"] + '</option>');
            		}
            	}
            }
          });
        $('.sort-select#sort2').show();
	}
	
	
	function upload_img(input) {
		$('#img_id').remove();
		$("#div_id_photo .img").css("display","block");
    	$("#div_id_photo .img").append('<img id="img_id" src="#" alt="your image" />');
    	
        if (input.files && input.files[0]) {

            var reader = new FileReader();
			
            reader.onload = function (e) {
            	var img = new Image();
            	img.src = e.target.result;
            	img.onload = function () {
            		if (this.width < 350 || this.height<350){
            			$("p.errorlist").append("La imagen debe tener un minimo de 350px de ancho y alto")
            		}else{
            			$("p.errorlist").text("");
            		}

                	$('#img_id').attr('src', this.src );
            	}
            	
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

</script>
</div>
{% endblock %}

templates/song/admin/listAlbum.html
{% extends 'base.html' %}

{% block title %}
Todos los albums - Hits Música
{% endblock %}


{% block styles %}

<div id="target-style">
	<link rel="stylesheet" type="text/css" href="/static/css/list.css">
</div>

{% endblock %}

{% block body %}

<div id="target-body">
<table>
	<thead>
		<tr>
			<td>Titulo</td>
			<td>Ano</td>
			<td>Portada</td>
			<td>Autores</td>
			<td>Canciones</td>
		</tr>
	</thead>
	
	<tbody>
		{% if object_list %}
			{% for album in object_list %}
				<tr>
					<td><a href="{% url 'player:detail_album' album.id %}">{{ album.name}}</a></td>
					<td>{{ album.year }}</td>
					<td><img class="" src="/{{album.photo}}" width="50" heigth="50"/></td>
					<td>{{ artist.name }}</td>
					<td>{{ album.song_set.all.count }}</td>
					<td> <button>
					     	<a href="{% url 'player:editar_album_song' album.id %}">Editar</a>
     					 </button>
     					 <button>
					     	<a href="{% url 'player:delete_album' album.id %}">Eliminar</a>
					     </button>
					 </td>
				</tr>
			{% endfor %}
		
		{% else %}
			<h1> No hay albumes registradas </h1>
		{% endif %}
		
		
	</tbody>

</table>
</div>
{% endblock %}

templates/song/admin/listSong.html
{% extends 'base.html' %}


{% block title %}
Todos las canciones - Hits Música
{% endblock %}


{% block styles %}

<div id="target-style">
	<link rel="stylesheet" type="text/css" href="/static/css/list.css">
</div>

{% endblock %}

{% block body %}

<div id="target-body">
	<center>
		<form method="get" id="search-form" action="{% url 'player:listar_canciones' %}" class="">
	        <div class="form-group ">
	          <input type="text" class="form-control" name="search" placeholder="Buscar...">
	        </div>
	        <button type="submit" class="btn btn-danger"><i class="fa fa-search" aria-hidden="true"></i></button>
      	</form>
	</center>
<table>
	<thead>
		<tr>
			<th>Titulo</th>
			<th>Lanzamiento</th>
			<th>Portada</th>
			<th>Autores</th>
			<th>Album</th>
			<th>Genero</th>
			<th>Likes</th>
			<th>repro</th>
			<th>descargas</th>
			<th>Acciones</th>
		</tr>
	</thead>
	
	<tbody>
		{% if object_list %}
			{% for song in object_list %}
				<tr>
					<td><a href="{% url 'player:detail_cancion' song.slug %}">{{ song.name}}</a></td>
					<td>{{ song.release_date }}</td>
					<td><img class="" src="/{{song.photo}}" width="50" heigth="50"/></td>
					<td>{% for artist in song.artists.all %}
						{{ artist.name }},
					{% endfor %}</td>
					<td>{{ song.album.name }}</td>
					<td>{{ song.genre.name }}</td>
					<td><center>{{ song.likes.count }}</center></td>
					<td><center>{{ song.num_views }}</center></td>
					<td><center>{{ song.num_downloads }}</center></td>
					<td> <button>
					     	<a href="{% url 'player:editar_cancion' song.id %}">Editar</a>
     					 </button>
					 </td>
				</tr>
			{% endfor %}
		
		{% else %}
			<h1> No hay canciones registradas </h1>
		{% endif %}
		
		
	</tbody>

</table>

	<div class="text-center">
                {% if object_list.has_other_pages %}
                    <ul class="pagination text-center">
                        {% if object_list.has_previous %}
                            <li><a class="link-pag" href="?search={{request.GET.search}}&page={{ object_list.previous_page_number }}">&laquo;</a></li>
                        {% else %}
                            <li class="disabled"><span>&laquo;</span></li>
                        {% endif %}
                        {% for i in object_list.paginator.page_range %}
                            {% if object_list.number == i %}
                                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                            {% else %}
                                <li><a class="link-pag" href="?search={{request.GET.search}}&page={{ i }}">{{ i }}</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if object_list.has_next %}
                            <li><a class="link-pag"  href="?search={{request.GET.search}}&page={{ object_list.next_page_number }}">&raquo;</a></li>
                        {% else %}
                            <li class="disabled"><span>&raquo;</span></li>
                        {% endif %}
                    </ul>
                {% endif %}
            </div>
</div>
{% endblock %}